apiVersion: v1
entries:
  ccsv:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.424430117-04:00"
    description: A Helm chart for Kubernetes
    digest: e164a9c8ae1db91721e8622e4c3449b917bea74f7b10794a6662ca357e88bced
    name: ccsv
    type: application
    urls:
    - ccsv-0.1.0.tgz
    version: 0.1.0
  convert-json:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.425267331-04:00"
    description: A Helm chart for Kubernetes
    digest: 6cb63dbfe0f7b3f076348037ee3bb58575a3f9874af224d151fc70fa28c9fa65
    name: convert-json
    type: application
    urls:
    - convert-json-0.1.0.tgz
    version: 0.1.0
  drop-duplicates:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.427436612-04:00"
    description: A Helm chart for Kubernetes
    digest: e327118dcb9a91aceb852cf3fa825c04bb986292eef441c56d5445c063a5e7f1
    name: drop-duplicates
    type: application
    urls:
    - drop-duplicates-0.1.0.tgz
    version: 0.1.0
  main-service-v1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.448350972-04:00"
    description: A Helm chart for Kubernetes
    digest: 210bc2347b266b86bb1ec598d9896bfe7265015e724547952e98357a1bde1a05
    name: main-service-v1
    type: application
    urls:
    - main-service-v1-0.1.0.tgz
    version: 0.1.0
  main-service-v1-tm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.468046776-04:00"
    description: A Helm chart for Kubernetes
    digest: 530a4febdbf2fe05fab8b4d77fa7c15a46c8a83342c75b9259d0f2166b3a6470
    name: main-service-v1-tm
    type: application
    urls:
    - main-service-v1-tm-0.1.0.tgz
    version: 0.1.0
  main-service-v2:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.469092644-04:00"
    description: A Helm chart for Kubernetes
    digest: 026a2c88ed98fcbd90eb622c126a413a3ebfe489fe50b24b1c50d22c77ee8721
    name: main-service-v2
    type: application
    urls:
    - main-service-v2-0.1.0.tgz
    version: 0.1.0
  main-service-v2-tm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.469982426-04:00"
    description: A Helm chart for Kubernetes
    digest: 919901b61290c53c4ac69f028730001b88d0bcbf8a72f76da0f904210d99706a
    name: main-service-v2-tm
    type: application
    urls:
    - main-service-v2-tm-0.1.0.tgz
    version: 0.1.0
  sort-data:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.470635329-04:00"
    description: A Helm chart for Kubernetes
    digest: 5eea7c9c4fefc41d65bfaad783b2e0f2ce1fb930983788c961aa71cd78816efc
    name: sort-data
    type: application
    urls:
    - sort-data-0.1.0.tgz
    version: 0.1.0
  validate-json-input:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-06-02T02:37:23.472852321-04:00"
    description: A Helm chart for Kubernetes
    digest: f7dcf2757debec2efdfb7a2e3a1c1d88feabae54be96ebd5b669d411365b8a58
    name: validate-json-input
    type: application
    urls:
    - validate-json-input-0.1.0.tgz
    version: 0.1.0
generated: "2023-06-02T02:37:23.41915752-04:00"
